# Generated by Django 3.2.23 on 2024-02-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_post_ti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ti',
            new_name='title',
        ),
    ]
